version: '3.9'
services:
  neo4j:
    container_name: spotify
    build: .
    image: neo4j_gdb
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./logs:/logs
      - ./plugins:/plugins